name: conventional-pr
on:
  pull_request:
    branches:
      - main
      - master
    types:
      - opened
      - edited
      - synchronize
jobs:
  label:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    name: Lint PR
    steps:
      - name: label
        uses: action-runner/conventional-labeler@2.0.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
  outdater:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    name: Dependencies outdater
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - name: Dependencies Outdater
        uses: action-runner/dependencies-outdater@master
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
